In [54]:
import pandas as pd
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score

In [55]:
# df = pd.read_csv("letter-recognition.data.txt", header = None)

# X = df[df.columns[1:]]
# Y = df[0]

# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.30, random_state = 30)

In [60]:
dataset = 'model/gesture_classifier/gesture_train_akshay.csv'
#dataset = 'model/gesture_classifier/gesture_train_kailash.csv'

column_names = ['class', '1', '2', '3', '4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43','44','45']

X_column_names = ['1', '2', '3', '4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43','44','45']

df = pd.read_csv(dataset, header = None, names=column_names)
df = df.dropna(how='any')

# Shuffling the dataset
df = df.sample(frac=1)

df.head()

class         1    2         3         4         5         6         7  \
5716    0.0 -0.410256  0.0 -0.096154 -0.371795  0.205128 -0.346154  0.339744   
1515    2.0 -0.227848  0.0  0.012658 -0.234177  0.259494 -0.132911  0.284810   
363     2.0 -0.364865  0.0 -0.195946 -0.216216  0.141892 -0.222973  0.324324   
415     2.0 -0.344371  0.0 -0.192053 -0.165563  0.132450 -0.052980  0.238411   
1295    2.0 -0.229814  0.0 -0.012422 -0.248447  0.223602 -0.149068  0.267081   

             8         9  ...        36        37        38        39  \
5716 -0.211538  0.044872  ... -0.782051 -0.269231  0.006410 -0.256410   
1515 -0.132911 -0.063291  ... -0.607595 -0.253165 -0.025316 -0.208861   
363  -0.195946 -0.216216  ... -0.844595 -0.290541  0.054054 -0.263514   
415  -0.019868 -0.066225  ... -0.735099 -0.324503  0.006623 -0.278146   
1295 -0.130435 -0.068323  ... -0.596273 -0.248447 -0.031056 -0.198758   

            40        41        42        43        44        45  
5716 -0.083333 -0.237179 -0.141026  0.182390 -0.262821 -0.179487  
1515 -0.145570 -0.164557 -0.221519 -0.613924 -0.164557  0.367089  
363  -0.074324 -0.189189 -0.135135 -0.810811 -0.155405  0.054054  
415  -0.112583 -0.211921 -0.158940 -0.794702  0.185430 -0.105960  
1295 -0.155280 -0.149068 -0.217391 -0.645963 -0.043478  0.267081  

[5 rows x 46 columns]

In [61]:
X = df.iloc[:, 1:]
Y = df.iloc[:, :1]

# print(X.head)
# print(Y.head)

print(X)
print(Y)

             1    2         3         4         5         6         7  \
5716 -0.410256  0.0 -0.096154 -0.371795  0.205128 -0.346154  0.339744   
1515 -0.227848  0.0  0.012658 -0.234177  0.259494 -0.132911  0.284810   
363  -0.364865  0.0 -0.195946 -0.216216  0.141892 -0.222973  0.324324   
415  -0.344371  0.0 -0.192053 -0.165563  0.132450 -0.052980  0.238411   
1295 -0.229814  0.0 -0.012422 -0.248447  0.223602 -0.149068  0.267081   
...        ...  ...       ...       ...       ...       ...       ...   
2923 -0.397351  0.0 -0.198675 -0.357616  0.258278 -0.364238  0.410596   
661  -0.207101  0.0 -0.029586 -0.278107  0.201183 -0.112426  0.213018   
5377 -0.371795  0.0 -0.173077 -0.384615  0.089744 -0.352564  0.269231   
5203 -0.401274  0.0 -0.171975 -0.426752  0.089172 -0.363057  0.267516   
4168 -0.241611  0.0 -0.214765 -0.315436  0.154362 -0.281879  0.322148   

             8         9        10  ...        36        37        38  \
5716 -0.211538  0.044872 -0.455128  ... -0.782051 

## Using Decision Tree

In [62]:
dtree_cv = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)

scores_dtree = cross_val_score(dtree_cv, X, Y, cv = 5, scoring = 'accuracy')
print(scores_dtree)
print("Cross Validation accuracy using Decision Tree",scores_dtree.mean())

dtree = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.80, random_state = 30)

dtree.fit(X_train, Y_train)
Y_pred_dtree = dtree.predict(X_test)

print("Accuracy using Decision Tree =", accuracy_score(Y_test, Y_pred_dtree))

print(Y_test[:10])

print(Y_pred_dtree[:10])

[0.99747475 0.99747475 0.99747475 0.9983165  0.99915825]
Cross Validation accuracy using Decision Tree 0.997979797979798
Accuracy using Decision Tree = 0.9964225589225589
      class
6034    0.0
940     2.0
4267    1.0
2148    2.0
2259    1.0
4019    1.0
3188    1.0
1914    2.0
408     2.0
1572    2.0
[0. 2. 1. 2. 1. 1. 1. 2. 2. 2.]


## Using KNN

In [75]:
dataset = 'model/gesture_classifier/gesture_train_akshay.csv'
#dataset = 'model/gesture_classifier/gesture_train_kailash.csv'

column_names = ['class', '1', '2', '3', '4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43','44','45']

X_column_names = ['1', '2', '3', '4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43','44','45']

df = pd.read_csv(dataset, header = None, names=column_names)
df.dropna(inplace=True)

# Shuffling the dataset
df = df.sample(frac=1)

# df = df.dropna(how='any', inplace=True)

df.head()

class         1    2         3         4         5         6         7  \
2413    1.0 -0.376623  0.0 -0.142857 -0.337662  0.162338 -0.337662  0.279221   
1047    2.0 -0.127273  0.0  0.103030 -0.218182  0.345455 -0.060606  0.272727   
1385    2.0 -0.198718  0.0 -0.019231 -0.205128  0.211538 -0.134615  0.282051   
4084    1.0 -0.346405  0.0 -0.124183 -0.326797  0.241830 -0.274510  0.346405   
1965    2.0 -0.271605  0.0 -0.117284 -0.265432  0.080247 -0.228395  0.172840   

             8         9  ...        36        37        38        39  \
2413 -0.253247 -0.045455  ... -0.740260 -0.311688 -0.006494 -0.259740   
1047 -0.024242 -0.024242  ... -0.630303 -0.218182 -0.024242 -0.187879   
1385 -0.108974 -0.096154  ... -0.698718 -0.217949  0.006410 -0.230769   
4084 -0.137255  0.019608  ... -0.738562 -0.261438  0.006536 -0.261438   
1965 -0.141975 -0.086420  ... -0.808642 -0.234568  0.018519 -0.197531   

            40        41        42        43        44        45  
2413 -0.103896 -0.233766 -0.149351 -0.311688  0.064935 -0.168831  
1047 -0.145455 -0.157576 -0.200000 -0.672727  0.357576 -0.084848  
1385 -0.108974 -0.224359 -0.198718 -0.634615  0.250000 -0.243590  
4084 -0.104575 -0.202614 -0.163399 -0.117647 -0.150327 -0.111111  
1965 -0.080247 -0.166667 -0.129630 -0.524691  0.037037  0.012346  

[5 rows x 46 columns]

In [76]:
from sklearn.neighbors import KNeighborsClassifier

print("Using 3-NN")

knn=KNeighborsClassifier(n_neighbors=3, metric='euclidean')
knn.fit(X_train, Y_train)

predictions = knn.predict(X_test)

print(classification_report(Y_test,predictions))
print("Confusion Matrix")
print(confusion_matrix(Y_test,predictions))
print("\n Accuracy")
print(accuracy_score(Y_test,predictions))

# k (5)- fold method for training and testing split and check the difference in performance of 3-NN¶

print("Using 3-NN after 5-fold cross-validation")

from sklearn.model_selection import cross_val_score
knn_cv = KNeighborsClassifier(n_neighbors=3, metric = 'euclidean')
scores = cross_val_score(knn_cv, X, Y, cv=5, scoring='accuracy')
print('scores: ', scores)
print('mean score: ', scores.mean())

# Normalize the dataset and apply 3-NN using both euclidean and manhattan distance

from sklearn import preprocessing
import numpy as np
from sklearn.model_selection import cross_val_score
for col in df.columns[:-1]:
    df[col] = (df[col]-df[col].min())/(df[col].max()-df[col].min())

X = df[df.columns[:-1]] # Selecting the independent variables
Y=df[df.columns[len(df.columns)-1]] # selecting only the target lableled column

knn_cv_euclidean = KNeighborsClassifier(n_neighbors=3, metric = 'euclidean')
scores_euclidean = cross_val_score(knn_cv_euclidean, X, Y, cv=5, scoring='accuracy')
print("scores euclidean: ", scores_euclidean)
print('mean score: ', scores_euclidean.mean())

knn_cv_manhattan = KNeighborsClassifier(n_neighbors=3, metric = 'manhattan')
scores_manhattan = cross_val_score(knn_cv_manhattan, X, Y, cv=5, scoring='accuracy')
print("scores manhattan: ", scores_manhattan)
print('mean score: ', scores_manhattan.mean())


# Plotting the accuracy for different values of Ks

k_scores=[]

for k in range(1,21):
    knn_iter = KNeighborsClassifier(n_neighbors=k,metric = 'euclidean')
    scores = cross_val_score(knn_iter, X, Y, cv=5, scoring='accuracy')
    k_scores.append(scores.mean())
    print(k,' scores: ', k_scores)

    
#### Write your answer here ####
import matplotlib.pyplot as plt
%matplotlib inline

k_range = list(range(1, 21))
plt.plot(k_range, k_scores)
plt.xlabel('Value of K for KNN')
plt.ylabel('Cross-Validated Accuracy')

print('maximum score: ', max(k_scores))
print('Best K value: ', k_scores.index(max(k_scores))+1)

Using 3-NN
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1333
         1.0       1.00      1.00      1.00      1672
         2.0       1.00      1.00      1.00      1747

    accuracy                           1.00      4752
   macro avg       1.00      1.00      1.00      4752
weighted avg       1.00      1.00      1.00      4752

Confusion Matrix
[[1328    2    3]
 [   4 1668    0]
 [   0    1 1746]]

 Accuracy
0.997895622895623
Using 3-NN after 5-fold cross-validation


C:\Users\agola\AppData\Roaming\Python\Python38\site-packages\sklearn\neighbors\_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


ValueError: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\agola\AppData\Roaming\Python\Python38\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\agola\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\agola\AppData\Roaming\Python\Python38\site-packages\sklearn\neighbors\_classification.py", line 233, in fit
    return self._fit(X, y)
  File "C:\Users\agola\AppData\Roaming\Python\Python38\site-packages\sklearn\neighbors\_base.py", line 456, in _fit
    X, y = self._validate_data(
  File "C:\Users\agola\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py", line 622, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\agola\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py", line 1146, in check_X_y
    X = check_array(
  File "C:\Users\agola\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py", line 957, in check_array
    _assert_all_finite(
  File "C:\Users\agola\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py", line 122, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "C:\Users\agola\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py", line 171, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
KNeighborsClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values


## Using Naive Bayes

In [48]:
# import Classifier library
from sklearn.naive_bayes import GaussianNB

# Call the Classifier
nb=GaussianNB()

predictions = nb.fit(X_train, Y_train).predict(X_test)

print("Number of mislabeled points: ")
#(X_test.shape[0], (Y_test != predictions).sum())


predictions = nb.predict(X_test)

# Calculate and print confusion matrix and other performance measures (Refer previous labsheet)

print(classification_report(Y_test,predictions))
print("Confusion Matrix")
print(confusion_matrix(Y_test,predictions))
print("\n Accuracy")
print(accuracy_score(Y_test,predictions))

Number of mislabeled points: 
              precision    recall  f1-score   support

         0.0       0.99      0.98      0.99      1328
         1.0       0.99      0.99      0.99      1668
         2.0       0.98      1.00      0.99      1756

    accuracy                           0.99      4752
   macro avg       0.99      0.99      0.99      4752
weighted avg       0.99      0.99      0.99      4752

Confusion Matrix
[[1306   11   11]
 [   7 1643   18]
 [   0    7 1749]]

 Accuracy
0.9886363636363636


C:\Users\agola\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## Using Bagging classifiers

In [ ]:
model = BaggingClassifier(base_estimator = dtree, n_estimators = 5, random_state = 30)

scores_model = cross_val_score(model, X, Y, cv = 5, scoring = 'accuracy')
print(scores_model)
print("Mean Ensemble Cross Validation accuracy by manipulating dataset",scores_model.mean())
model = model.fit(X_train, Y_train)
Y_pred_model = model.predict(X_test)

print("Ensemble Accuracy by manipulating dataset =", accuracy_score(Y_test, Y_pred_model))

## Using Different Classifiers

In [15]:
# Question 2

from sklearn.ensemble import VotingClassifier

dt_entropy = DecisionTreeClassifier(criterion = 'gini', random_state = 30)
k3 = KNeighborsClassifier(n_neighbors = 3, metric = 'euclidean')
k5_euclidean = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean')
k5_manhattan = KNeighborsClassifier(n_neighbors = 5, metric = 'manhattan')
nb = GaussianNB()

voting_clf = VotingClassifier(estimators = [('DT', dt_entropy), ('K3' ,k3), ('k5E', k5_euclidean), ('K5M', k5_manhattan), ('NB', nb)], voting = 'hard')

#voting_clf.fit(X_train, Y_train)

scores = cross_val_score(voting_clf, X, Y, cv = 5, scoring = 'accuracy')

print(scores)
# print("Mean Cross Validation accuracy using Bagging by manipulating classifiers",scores.mean())

# Y_pred = voting_clf.predict(X_test)

# print("Accuracy by manipulating classifiers =", accuracy_score(Y_test, Y_pred))



[0.94321429 0.945      0.94142857 0.94821429 0.94678571]
Mean Cross Validation accuracy using Bagging by manipulating classifiers 0.9449285714285713


NotFittedError: This VotingClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [6]:
# Question 3

import numpy as np

vector = []

for i in range(5):
    v = np.random.choice(np.arange(1, 17),10, replace = False)
    vector.append(v)


df1 = df.loc[:,vector[0]]
df2 = df.loc[:,vector[1]]
df3 = df.loc[:,vector[2]]
df4 = df.loc[:,vector[3]]
df5 = df.loc[:,vector[4]]


In [7]:
X1 = df1[df1.columns[0:]]
Y1 = df[df.columns[0]]

X_train, X_test, Y_train, Y_test = train_test_split(X1, Y1, test_size = 0.30, random_state = 30)


dtree1 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
dtree1.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=30)

In [8]:
X2 = df2[df2.columns[0:]]
Y2 = df[df.columns[0]]

X_train, X_test, Y_train, Y_test = train_test_split(X2, Y2, test_size = 0.30, random_state = 30)


dtree2 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
dtree2.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=30)

In [9]:
X3 = df3[df3.columns[0:]]
Y3 = df[df.columns[0]]

X_train, X_test, Y_train, Y_test = train_test_split(X3, Y3, test_size = 0.30, random_state = 30)


dtree3 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
dtree3.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=30)

In [10]:
X4 = df4[df4.columns[0:]]
Y4 = df[df.columns[0]]

X_train, X_test, Y_train, Y_test = train_test_split(X4, Y4, test_size = 0.30, random_state = 30)


dtree4 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
dtree4.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=30)

In [11]:
X5 = df5[df5.columns[0:]]
Y5 = df[df.columns[0]]

X_train, X_test, Y_train, Y_test = train_test_split(X5, Y5, test_size = 0.30, random_state = 30)


dtree5 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
dtree5.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=30)

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.30, random_state = 30)

clf = VotingClassifier(estimators = [('DT1', dtree1), ('DT2' ,dtree2), ('DT3', dtree3), ('DT4', dtree4), ('DT5', dtree5)], voting = 'hard')

clf.fit(X_train, Y_train)

scores = cross_val_score(clf, X_train, Y_train, cv = 5, scoring = 'accuracy')

print(scores)
print("Mean Ensemble Cross Validation by manipulating features =",scores.mean())

Y_pred = clf.predict(X_test)

print("Ensemble Accuracy using by manipulating features =", accuracy_score(Y_test, Y_pred))


[0.865      0.86964286 0.85214286 0.86       0.87      ]
Mean Ensemble Cross Validation by manipulating features = 0.8633571428571427
Ensemble Accuracy using by manipulating features = 0.8651666666666666


In [13]:
# Question 4

vector = []

for i in range(5):
    v = np.random.choice(np.arange(1, 26),13, replace = False)
    vector.append(v)


df1 = df.copy (deep = True)
df2 = df.copy (deep = True)
df3 = df.copy (deep = True)
df4 = df.copy (deep = True)
df5 = df.copy (deep = True)


for row in range(df.shape[0]):
    
    col = ord(df.iloc[row, 0]) - 64
    
    if col in vector[0]:
        df1.iloc[row, 0] = '1'
    else:
        df1.iloc[row, 0] = '0'
    
    if col in vector[1]:
        df2.iloc[row, 0] = '1'
    else:
        df2.iloc[row, 0] = '0'
    
    
    if col in vector[2]:
        df3.iloc[row, 0] = '1'
    else:
        df3.iloc[row, 0] = '0'
        
    if col in vector[3]:
        df4.iloc[row, 0] = '1'
    else:
        df4.iloc[row, 0] = '0'
        
    if col in vector[4]:
        df5.iloc[row, 0] = '1'
    else:
        df5.iloc[row, 0] = '0'
        

In [14]:
X1 = df1[df1.columns[1:]]
Y1 = df1[df1.columns[0]]

X_train, X_test, Y_train, Y_test = train_test_split(X1, Y1, test_size = 0.30, random_state = 30)


Dtree1 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
Dtree1.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=30)

In [15]:
X2 = df2[df2.columns[1:]]
Y2 = df2[df2.columns[0]]

X_train, X_test, Y_train, Y_test = train_test_split(X2, Y2, test_size = 0.30, random_state = 30)


Dtree2 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
Dtree2.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=30)

In [16]:
X3 = df3[df3.columns[1:]]
Y3 = df3[df3.columns[0]]

X_train, X_test, Y_train, Y_test = train_test_split(X3, Y3, test_size = 0.30, random_state = 30)


Dtree3 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
Dtree3.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=30)

In [17]:
X4 = df4[df4.columns[1:]]
Y4 = df4[df4.columns[0]]

X_train, X_test, Y_train, Y_test = train_test_split(X4, Y4, test_size = 0.30, random_state = 30)


Dtree4 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
Dtree4.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=30)

In [18]:
X5 = df5[df5.columns[1:]]
Y5 = df5[df5.columns[0]]

X_train, X_test, Y_train, Y_test = train_test_split(X5, Y5, test_size = 0.30, random_state = 30)


Dtree5 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
Dtree5.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=30)

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.30, random_state = 30)

clf2 = VotingClassifier(estimators = [('DT_1', Dtree1), ('DT_2' ,Dtree2), ('DT_3', Dtree3), ('DT_4', Dtree4), ('DT_5', Dtree5)], voting = 'hard')

clf2.fit(X_train, Y_train)

scores = cross_val_score(clf2, X_train, Y_train, cv = 5, scoring = 'accuracy')

print(scores)
print("Mean Ensemble Cross Validation by manipulating classes =",scores.mean())

Y_pred = clf2.predict(X_test)

print("Ensemble Accuracy using by manipulating classes =", accuracy_score(Y_test, Y_pred))

[0.865      0.86964286 0.85214286 0.86       0.87      ]
Mean Ensemble Cross Validation by manipulating classes = 0.8633571428571427
Ensemble Accuracy using by manipulating classes = 0.8651666666666666


In [20]:
# Question 5

print("The Ensemble classifier by manipulating classifier performs best with accuracy of 94.9% .")
print("Ensemble classifiers by manipulating classes and manipulating features  perform with identical accuracy of 86.51% .")
print(" The Ensemble classifier by manipulation of dataset obtained accuracy of 89.2%")

The Ensemble classifier by manipulating classifier performs best with accuracy of 94.9% .
Ensemble classifiers by manipulating classes and manipulating features  perform with identical accuracy of 86.51% .
 The Ensemble classifier by manipulation of dataset obtained accuracy of 89.2%


In [21]:
Dtree1 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
Dtree2 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
Dtree3 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
Dtree4 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)
Dtree5 = DecisionTreeClassifier(criterion = 'entropy', random_state = 30)

clf2 = VotingClassifier(estimators = [('DT_1', Dtree1), ('DT_2' ,Dtree2), ('DT_3', Dtree3), ('DT_4', Dtree4), ('DT_5', Dtree5)], voting = 'hard')

clf2.fit(X_train, Y_train)

scores = cross_val_score(clf2, X_train, Y_train, cv = 5, scoring = 'accuracy')

print(scores)
print("Mean Ensemble Cross Validation by manipulating classes =",scores.mean())

Y_pred = clf2.predict(X_test)

print("Ensemble Accuracy using by manipulating classes =", accuracy_score(Y_test, Y_pred))

[0.865      0.86964286 0.85214286 0.86       0.87      ]
Mean Ensemble Cross Validation by manipulating classes = 0.8633571428571427
Ensemble Accuracy using by manipulating classes = 0.8651666666666666
